networks:
  expense: {}
volumes:
  mysql:
services:
# docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: lakshman143/mysql:1.0.0
    container_name: mysql
    networks:
    - expense
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: lakshman143/backend:1.0.0
    command: sh -c "sleep 5 && node /opt/backend/index.js"
    container_name: backend
    networks:
    - expense
    depends_on:
    - mysql
  frontend:
    image: lakshman143/frontend:1.0.0
    container_name: frontend
    networks:
    - expense
    ports:
    - 80:80
    depends_on:
    - backend